language: php

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: 8.0
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

env:
  global:
    - FORCE_COLOR=1

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml --whitelist lib --bootstrap vendor/autoload.php tests

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: release
      language: node_js
      node_js: '8'
      install:
        - npm ci
      script:
        - npm run semantic-release
      after_success: false

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

branches:
  except:
   - /^v\d+\.\d+\.\d+$/
